#! /bin/bash

name=pgfortran_mpich2-1.3.1_fast_nemesis
name=pgfortran_mpich2-1.4.1p1_fast_nemesis
###########################

zempi=1.3.1
zempi=1.4.1p1

wget http://www.mcs.anl.gov/research/projects/mpich2/downloads/tarballs/$zempi/mpich2-$zempi.tar.gz
tar xzvf mpich2-$zempi.tar.gz
\rm mpich2-$zempi.tar.gz

export CC=pgcc 
export FC=pgfortran 
export F77=pgfortran 
export CXX=pgcpp 
export CFLAGS=-fast 
export FCFLAGS=-fast 
export FFLAGS=-fast 
export CXXFLAGS=-fast 

ici=$PWD/$name
cd mpich2-$zempi
./configure --prefix=$ici --with-device=ch3:nemesis
make
make install
cd ..
\rm -rf mpich2-$zempi


