#! /bin/bash

#---------------------------------------#
# A script to install the model         #
#---------------------------------------#
# Author: Aymeric Spiga - November 2008 #
#---------------------------------------#


touch download_log

mkdir SRC
cd SRC/

mv ../g95.tar.gz .
mv ../mac.tar.gz .
mv ../datesave .
mv ../saved .
mv ../INIT_SIMPLE_TEST.tar.gz .
mv ../POSTPROC.tar.gz .

echo 1/8 get WRF sources
wget http://www.mmm.ucar.edu/wrf/src/WRFV2.2.TAR.gz . >> ../download_log 2>> ../download_log
tar xzvf WRFV2.2.TAR.gz > /dev/null
\rm WRFV2.2.TAR.gz 
## patch
wget http://www.mmm.ucar.edu/wrf/src/fix/rsl_bcast.c . >> ../download_log 2>> ../download_log
mv -f rsl_bcast.c WRFV2/external/RSL_LITE/
wget http://www.mmm.ucar.edu/wrf/src/fix/solve_em.F.fix . >> ../download_log 2>> ../download_log
mv -f solve_em.F.fix WRFV2/dyn_em/solve_em.F
## patch

echo 2/8 get WPS sources
wget wget http://www.mmm.ucar.edu/wrf/src/WPSV2.2.TAR.gz . >> ../download_log 2>> ../download_log
tar xzvf WPSV2.2.TAR.gz > /dev/null
\rm WPSV2.2.TAR.gz

echo 3/8 get WRF modified Martian sources
mv ../sources_Mars.tar.gz .
tar xzvf sources_Mars.tar.gz > /dev/null
cp -rf save/* WRFV2/
\rm -rf save
\rm sources_Mars.tar.gz 

echo 4/8 get WPS modified Martian sources
mv ../WPS.tar.gz .
tar xzvf WPS.tar.gz > /dev/null
cd WPS
#cp -f /donnees/aslmd/WRF/SRC/WPS/wps_mars/switch_WPS_Mars .
./switch_WPS_Mars
cd ..
\rm WPS.tar.gz

echo 5/8 get ARWpost for Mars
mv ../ARWpost.tar.gz .
tar xzvf ARWpost.tar.gz > /dev/null
\rm ARWpost.tar.gz

echo 6/8 get PREP_MARS
mv ../PREP_MARS.tar.gz .
tar xzvf PREP_MARS.tar.gz > /dev/null
\rm PREP_MARS.tar.gz

cd ..

echo 7/8 get surface data utilities
tar xzvf WPS_GEOG.tar.gz > /dev/null
wget http://web.lmd.jussieu.fr/~forget/datagcm/datafile/dust_tes.nc . >> ./download_log 2>> ./download_log
mv dust_tes.nc WPS_GEOG/
\rm WPS_GEOG.tar.gz

echo 8/8 get run utilies
tar xzvf SIMU.tar.gz > /dev/null
\rm SIMU.tar.gz

echo ok
