          integer Nline_mx,Nmol_max,Niso_max,Nbmx,Nkmx,Nmax,Nlpnb_mx
	    integer Nxtab_mx,Nacc_mx,Nmax_tab,Nytab_mx,Nktab_mx
	    integer nfiles_mx,Nproc_mx,Nchunk_mx,Nc_mx,Nmax_vt,Nppc_max
	    integer Nti_mx
          parameter(Nline_mx=2000000)
          parameter(Nmol_max=42)
          parameter(Niso_max=15)
	  parameter(Nbmx=10000)
	  parameter(Nkmx=100000)
	  parameter(Nmax=2000)
	  parameter(Nlpnb_mx=500000)
	  parameter(Nxtab_mx=100000)
	  parameter(Nacc_mx=1000)
	  parameter(Nmax_tab=1000000)
	    parameter(Nytab_mx=210)
	    parameter(Nktab_mx=1000000)
	    parameter(nfiles_mx=100)
	    parameter(Nproc_mx=1000)
	    parameter(Nchunk_mx=1000)
	    parameter(Nc_mx=9)
	    parameter(Nmax_vt=1000000)
	    parameter(Nppc_max=10000)
	    parameter(Nti_mx=100000)
