#! /bin/bash

#wget http://www.lmd.jussieu.fr/~hourdin/PATCH_LMDZ4OR_G95/netcdf-3.6.1.tar.gz
#gunzip netcdf-3.6.1.tar.gz
tar xvf netcdf-3.6.1.tar

#cp /donnees/emlmd/Downloads/Software/netcdf-4.0.1.tar.gz .
#gunzip netcdf-4.0.1.tar.gz
#tar xvf netcdf-4.0.1.tar
#cd netcdf-4.0.1

here=$PWD
zename=g95_64_nosecondunderscore_netcdf-3.6.1

mkdir $zename
cd netcdf-3.6.1/src

export CPPFLAGS=-Df2cFortran
export CC=gcc
export CFLAGS="-O2"
export CXX=g++
export CXXFLAGS="-O2"
export FC=g95
export FFLAGS=" -cpp -O2 -fno-second-underscore"
#export F77=g95
#export CPP='gcc -E'
export F90=g95
export F90FLAGS=" -cpp -ffree-form -O2 -fno-second-underscore"

#export FCFLAGS='-O2 -fno-second-underscore'
#### enlever CPP ???
##FCFLAGS="-g -O2 -fno-second-underscore"
##FFLAGS="-g -O2 -fno-second-underscore"
#export CPPFLAGS=-DpgiFortran

./configure --prefix=$here/$zename > $here/$zename/configure.log 2>&1
make > $here/$zename/make.log 2>&1
make test > $here/$zename/make_test.log 2>&1
make install > $here/$zename/make_install.log 2>&1
