#! /bin/bash


#wget http://www.lmd.jussieu.fr/~hourdin/PATCH_LMDZ4OR_G95/netcdf-3.6.1.tar.gz
#gunzip netcdf-3.6.1.tar.gz
tar xvf netcdf-3.6.1.tar

cd netcdf-3.6.1

export CC=gcc 
export CXX=g++ 
export CPP='gcc -E' 
export FC=gfortran 
export F77=gfortran 
export F90=gfortran 
export CFLAGS='-O2 -DpgiFortran' 
export CXXFLAGS='-O2 -DpgiFortran' 
export CPPFLAGS='-DpgiFortran' 
export FFLAGS='-O2 -fno-second-underscore' 
export FCFLAGS='-O2 -fno-second-underscore' 
export F90FLAGS='-O2 -fno-second-underscore'

cd src
# Compilation
./configure
make check
make install

