MODULE  TGMDAT_MOD
      IMPLICIT NONE

      REAL,SAVE :: PI=3.14159265358979323846
! RGAS IS THE UNIVERSAL GAS CONSTANT IN UNITS OF: M SEC-2 AMU K-1 KM
      REAL,SAVE :: RGAS=8.31432
! SIGMA IS THE STEFAN-BOLTZMAN CONSTATNT IN CGS UNITS
      REAL,SAVE :: SIGMA=5.6677E-5
!
! RT CONSTANTS
      REAL,SAVE :: UBARI=0.5,UBARV=0.5,UBAR0=0.5
! PLANET SPECIFIC CONSTANTS
!
! CONVEQ IS THE DRY N2 ADIABATE DLNT/DLNP
      REAL,SAVE :: CONVEQ=0.2994
! CSUBP IS THE SPECIFIC HEAT AT CONSTANT P OF THE ATMOSPHERE
! IN UNITS OF ERGS K-1 G-1
      REAL,SAVE :: CSUBP=1.039E7
! RHOP IS THE UNITS CONVERSION FROM TO GET MASS UNITS (G CM-2)
! FROM PRESSURE (BARS)  DEVIDED BY GRAVITY (M SEC-2)
! IS EQUAL TO ONE  GM CM-2  BARS-1  M SEC-2
! IF ONE WHATS TO CHANGE UNITS ON PRESSURE THIS
! CONSTANT MUST BE CHANGED
      REAL,SAVE :: RHOP=1.E4
! FOPI IS THE ACTUAL SOLAR FLUX IN ERGS/CM2
      REAL,SAVE :: F0PI=1.5E4
! RHCH4 IS THE METHANE RH AT THE SURFACE
      REAL,SAVE :: RHCH4=0.60   !! .65
! FH2 IS THE CONSTANT MIXING RATIO OF H2
      REAL,SAVE :: FH2=0.04   !!  0.003
! FHAZE IS THE HAZE PRODUCTION SCALING FACTOR
      REAL,SAVE :: FHAZE=0.35
! FHIR IS THE HAZE INFRARED ABSORPTION SCALE FACTOR
      REAL,SAVE :: FHIR=0.7     ! anciennement 0.5
! FHVIS IS THE HAZE INFRARED ABSORPTION SCALE FACTOR
      REAL,SAVE :: FHVIS=1.1              !!!!  1.333333333/
! TAUFAC IS THE 200 CM-1 SCALING FACTOR
      REAL,SAVE :: TAUFAC=2.00
! RCLOUD IS THE PARTICLE SIZE IN THE CLOUD IN MICRONS
      REAL,SAVE ::RCLOUD=60.     !! 100

      REAL,SAVE :: FARGON=0.
END MODULE TGMDAT_MOD
